# Generated by Django 3.0.6 on 2020-05-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=255)),
                ('mdesc', models.CharField(max_length=255)),
                ('mimg', models.CharField(max_length=255)),
                ('mlink', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
    ]
